import git
from git_contributions_importer import *

repo = git.Repo("/Users/santiagochiesa/code/metyis/pepsico_pt/digital-spotter-pepsico-pt-2021")
mock_repo = git.Repo("/Users/santiagochiesa/code/sanchiesa/gitlab_commits")

importer = Importer([repo], mock_repo)
importer.set_author(['santiago.chiesa@metyis.com', 'chiesa.santiago@gmail.com'])

importer.import_repository()
print("ugefu")
print("ebuvh")
print("lctoo")
print("hjjkt")
print("tifgs")
print("tnbvn")
print("khwia")
print("vpemc")
print("mpubc")
print("byjwy")
print("stemk")
print("fdkgn")
print("wdquh")
print("eopow")
print("xueby")
print("bxogv")
print("gktmc")
print("lkivv")
print("kkuix")
print("iuyvx")
print("tyhdq")
print("ysnuu")
print("edxtb")
print("isngb")
print("xxypg")
print("umipr")
print("ccwsr")
print("ppbty")
print("ltatg")
print("ipxvv")
print("qvgme")
print("povdk")
print("dyyxv")
print("eapjo")
print("vfmkb")
print("ihfsn")
